version: "3.9"

services:
  server:
    image: your-dockerhub-username/frontend-app:latest   # dùng image đã build và push từ GitHub Actions
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    restart: unless-stopped
