import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google"; // Giữ lại nếu bạn sử dụng sau này
import "./globals.css";
import Header from "../components/customer/Header";
import Footer from "../components/customer/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
      >
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
