import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from "next/font/google"; // Giữ lại nếu bạn sử dụng sau này
import '~/app/globals.css';
import Header from '~/components/seller/header/SellerHeader';
import Sidebar from '~/components/seller/side-bar/SettingSidebar';
import MerchantSidebar from '~/components/seller/side-bar/MerchantSidebar';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function SellerLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <div className="h-screen flex flex-col overflow-hidden">
                    {/* Header cố định ở trên */}
                    <div className="sticky top-0 z-50">
                        <Header />
                    </div>

                    <div className="flex flex-1 overflow-hidden">
                        {/* Cột chứa cả 2 sidebar */}
                        <div className="sticky top-0 h-full z-40 flex">
                            <Sidebar />
                            <MerchantSidebar />
                        </div>

                        {/* Nội dung chính có thể scroll */}
                        <main className="flex-1 overflow-auto p-8 bg-gray-100">
                            {children}
                        </main>
                    </div>
                </div>
            </body>
        </html>
    );
}
