name: Frontend CI/CD

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Cài Node + pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 3. Cài lib + build FE
      - name: Install dependencies
        run: pnpm install

      - name: Build frontend
        run: pnpm run build

      # Copy chỉ build folder + docker-compose.yml
      - name: Copy build files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            .next
            package.json
            pnpm-lock.yaml
            docker-compose.yml
          target: "~/frontend-app"

      - name: Restart frontend service
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/frontend-app
            docker compose down
            docker compose up -d
            echo "Deployed at $(date)" > deployed.log

